namespace YMMProjectManager.Application.TimelineCore;

public sealed record DiffTimelinePreviewWorkspaceState(
    DiffTimelineFilterState? FilterState,
    string GroupingMode,
    DiffTimelineSnapshotBrowserState SnapshotBrowserState,
    DiffTimelineReusableCompareSession? SelectedCompareSession,
    string LatestCompareResultSummary,
    string LatestValidationLogPath,
    string LatestDiagnosticsPath,
    string LatestExportPath,
    IReadOnlyList<string> LatestWarnings,
    IReadOnlyList<string> LatestErrors,
    DiffTimelineRenderMetrics? RenderMetrics,
    DiffTimelineVirtualizationState? VirtualizationState,
    DiffTimelineHeavyProjectDiagnostics? HeavyProjectDiagnostics,
    DiffTimelineProjectionCacheStats? ProjectionCacheStats,
    bool IsLargeResultMode,
    string LargeResultModeReason,
    int MaterializedRowLimit,
    int TotalAvailableRowCount,
    int DisplayedRowCount,
    int DeferredRowCount,
    int VisibleRowWindowStart,
    int VisibleRowWindowSize,
    bool CanLoadMoreRows);
